// This file is automatically generated. Do not edit manually.
export const photos = [
  {
    id: 1,
    url: 'https://lh3.googleusercontent.com/d/1BZGevr_k7A8IrZQNQrtmrqw78F1tpNdq',
    title: 'Dscf4387 1',
    date: '2026-08-05T22:36:24.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 2,
    url: 'https://lh3.googleusercontent.com/d/1AbV5Jtdi19xq8mIJ5Mo-jST2gAxBeC6o',
    title: 'Dscf4349',
    date: '2026-08-05T22:33:48.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 3,
    url: 'https://lh3.googleusercontent.com/d/1Nepw9DE4JD-RnQUOp1V8PlnADSPquSkp',
    title: 'Dscf4161',
    date: '2026-08-05T22:33:32.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 4,
    url: 'https://lh3.googleusercontent.com/d/1rc-HC1KBjHTpaJofwpz4CMP8Azie3XOT',
    title: 'Dscf4175',
    date: '2026-08-05T22:33:32.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 5,
    url: 'https://lh3.googleusercontent.com/d/1SuT3RS06gKgg8qMS1o_glEEm5P-CZ78i',
    title: 'Dscf4326',
    date: '2026-08-05T22:32:18.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 6,
    url: 'https://lh3.googleusercontent.com/d/15TpPGGKM0NqdPH87WHGBN4KNstEY9_HI',
    title: 'Dscf4168',
    date: '2026-08-05T22:31:12.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 7,
    url: 'https://lh3.googleusercontent.com/d/12uBGbbWORBstvoddxCLpXh_LoI7SCbYl',
    title: 'Dscf4176',
    date: '2026-08-05T22:31:12.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 8,
    url: 'https://lh3.googleusercontent.com/d/1X3jO9KPX_3uVxt89z38eXda61HvrZVgU',
    title: 'Dscf4336',
    date: '2026-08-05T22:30:28.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 9,
    url: 'https://lh3.googleusercontent.com/d/1pfma3HHcClfV7NK7gsXLZaNBpcJnVTP3',
    title: 'Dscf4374 1',
    date: '2026-08-05T22:30:06.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 10,
    url: 'https://lh3.googleusercontent.com/d/17OJ4g8QKy1Na8_-lGpEM_J6_y8yTh17R',
    title: 'Dscf4375',
    date: '2026-08-05T22:30:04.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 11,
    url: 'https://lh3.googleusercontent.com/d/1Pe4S9CCyHetTx0ByO1byYpl6lWXGANxC',
    title: 'Dscf4376 1',
    date: '2026-08-05T22:30:04.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 12,
    url: 'https://lh3.googleusercontent.com/d/1H2fHjbE520PGo8jJufxZZxRhf3tZvbyp',
    title: 'Dscf4363',
    date: '2026-08-05T22:30:02.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 13,
    url: 'https://lh3.googleusercontent.com/d/1BNxwNCmTelvn67-ayOse6jRllK52TYjR',
    title: 'Dscf4369',
    date: '2026-08-05T22:29:48.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 14,
    url: 'https://lh3.googleusercontent.com/d/1AsC_km-ZnaSb0YqyrsR2cS-fBAa_mvnI',
    title: 'Dscf4390',
    date: '2026-08-05T22:28:48.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 15,
    url: 'https://lh3.googleusercontent.com/d/1liiZRh7-VUiHPog7FG-omloE2lQPFj0c',
    title: 'Dscf4177',
    date: '2026-08-05T22:28:22.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 16,
    url: 'https://lh3.googleusercontent.com/d/14lbYH5To9Jj3xTWL76VBYOJIVDoYe7DX',
    title: 'Dscf4339',
    date: '2026-08-05T22:28:14.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 17,
    url: 'https://lh3.googleusercontent.com/d/1TfCu5K-kef2XWN9bcLNBKUVe9t0PS4Uo',
    title: 'Dscf4378',
    date: '2026-08-05T22:28:00.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 18,
    url: 'https://lh3.googleusercontent.com/d/1CWgvWi6weFcVxW3rvP1wQrA6RmBCD2VS',
    title: 'Dscf4331',
    date: '2026-08-05T22:27:50.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 19,
    url: 'https://lh3.googleusercontent.com/d/1zQREru38r6iJ2lf9cBhHnQt9jfZyljyA',
    title: 'Dscf4269',
    date: '2026-08-05T22:26:36.000Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 20,
    url: 'https://lh3.googleusercontent.com/d/1TJFDPhvTJJg6H7eDEsfG6pVdyhs5589q',
    title: 'Dscf4342',
    date: '2026-08-05T22:26:36.000Z',
    description: 'Imported from Google Drive.'
  }
];
