// This file is automatically generated. Do not edit manually.
export const photos = [
  {
    id: 1,
    url: 'https://lh3.googleusercontent.com/d/1WODy1PfmAutrO8icbMhm7bEuQOAcUaEN',
    title: 'Dscf5609',
    date: '2026-08-05T21:45:31.714Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 2,
    url: 'https://lh3.googleusercontent.com/d/1v9CaoAPf1y3tO3D1Q2e1kpOWo9644QWA',
    title: 'Dscf5410',
    date: '2026-08-05T21:45:28.479Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 3,
    url: 'https://lh3.googleusercontent.com/d/1MvSraNI-Py6o2NGrAQ7ZanxMXrWABhPI',
    title: 'Dscf5432',
    date: '2026-08-05T21:45:25.262Z',
    description: 'Imported from Google Drive.'
  },
  {
    id: 4,
    url: 'https://lh3.googleusercontent.com/d/1AKt3hZJfmnd3lFXel0D_YhX-rZltoYx-',
    title: 'Dscf5306',
    date: '2026-08-05T21:45:22.091Z',
    description: 'Imported from Google Drive.'
  }
];
