import json
import subprocess
import os

# Your Google Drive Folder ID
FOLDER_ID = '1EW1irRHgm62NmkYomUJvTedGNzPMIE8g'
GDRIVE_PATH = '/google/bin/releases/gemini-agents-gdrive/gdrive'
OUTPUT_FILE = 'photos.js'

def main():
    print("Fetching photos from Google Drive...")
    try:
        # Run gdrive command to list files in JSON format
        result = subprocess.run(
            [GDRIVE_PATH, 'readonly', 'ls', FOLDER_ID, '--json'],
            capture_output=True,
            text=True,
            check=True
        )
        
        files = json.loads(result.stdout)
        
        # Filter to only include images
        images = [f for f in files if f.get('mimeType', '').startswith('image/')]
        
        if not images:
            print("No images found in the Google Drive folder.")
            write_placeholders()
            return

        # Sort images by modifiedTime descending (newest first)
        # We use get('modifiedTime', '') and fallback to empty string if missing
        images.sort(key=lambda x: x.get('modifiedTime', ''), reverse=True)

        # Generate the content for photos.js
        js_content = "// This file is automatically generated. Do not edit manually.\n"
        js_content += "export const photos = [\n"
        for i, img in enumerate(images, 1):
            file_id = img['id']
            title = os.path.splitext(img['name'])[0].replace('_', ' ').replace('-', ' ').title()
            url = f"https://lh3.googleusercontent.com/d/{file_id}"
            date = img.get('modifiedTime', '')
            
            js_content += "  {\n"
            js_content += f"    id: {i},\n"
            js_content += f"    url: '{url}',\n"
            js_content += f"    title: '{title}',\n"
            js_content += f"    date: '{date}',\n" # Added date
            js_content += "    description: 'Imported from Google Drive.'\n"
            js_content += "  }"
            if i < len(images):
                js_content += ",\n"
            else:
                js_content += "\n"
        js_content += "];\n"

        # Write to photos.js
        with open(OUTPUT_FILE, 'w') as f:
            f.write(js_content)
            
        print(f"Success! Updated {OUTPUT_FILE} with {len(images)} sorted photos.")

    except subprocess.CalledProcessError as e:
        print(f"Error calling Google Drive CLI: {e.stderr}")
    except Exception as e:
        print(f"An error occurred: {e}")

def write_placeholders():
    placeholder_content = """export const photos = [
  {
    id: 1,
    url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    title: 'Yosemite Valley (Placeholder)',
    date: '2026-08-01T12:00:00.000Z',
    description: 'Add photos to your Google Drive folder and run update_gallery.py to replace this.'
  }
];
"""
    with open(OUTPUT_FILE, 'w') as f:
        f.write(placeholder_content)
    print("Wrote placeholder photo to photos.js")

if __name__ == '__main__':
    main()
